### ISSUE TITLE
Proper method for creating setup

### ISSUE THREAD

**Issue by Tooru1** [falahati/NiVirtualCam#3]
Hello,
I just saw your splendid NiVirtualCam and decided to add some voice recognition to it for my school project. I tried to create setup, but it gave me "NiWrapper.dll HRESULT 0x8007007E" error. I tried this method for creating setup.
http://www.youtube.com/watch?v=Lcue0jo41AM
but it doesn`t work, so can you please tell me the proper way for creating setup for NiVirtualCam? I downloaded all files from Github, but I can`t create a running setup.

Thank you in advance, Regards

**Comment by exoloner** [comment]
The main problem, using NSIS or not, is the lack of instructions to build the binaries, and then generate de SetUp.
VS2012 + . Windows SDK 7.1 

Failed to build the binaries:
nivirtualcam-master\nifilter\nivirtualcam.cpp(23): fatal error C1083: No se puede abrir el archivo incluir: 'streams.h': No such file or directory

**Comment by falahati** [comment]
Hi,
You NEED to install the Platform SDK (Windows SDK) and compile the "BaseClasses" project. Project properties should be ok unchanged, but you can double check if you failed to compile it.
