### ISSUE TITLE
constant crashes

### ISSUE THREAD

**Issue by spiffomatic64** [falahati/NiVirtualCam#4]
Im getting pretty consistent crashes (every 15 minutes or so)

Here is the crash logs from event viewer

Application: NiUI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
Stack:
   at System.Drawing.Image.get_Width()
   at System.Drawing.Image.get_Size()
   at NiUI.frm_Main.currentSensor_onNewFrame(OpenNIWrapper.VideoStream)
   at OpenNIWrapper.VideoStream.Internal_NewFrame(IntPtr)

Faulting application name: NiUI.exe, version: 0.9.5.0, time stamp: 0x51af8790
Faulting module name: KERNELBASE.dll, version: 6.1.7601.18409, time stamp: 0x53159a86
Exception code: 0xe0434352
Fault offset: 0x0000c42d
Faulting process id: 0x82c
Faulting application start time: 0x01cfe58151ffd183
Faulting application path: C:\Program Files (x86)\NiVirtualCam\NiUI.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 41d5adf0-51c6-11e4-aa25-0019dbb6535f

Fault bucket 3948686011, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: niui.exe
P2: 0.9.5.0
P3: 51af8790
P4: System.Drawing
P5: 4.0.30319.18408
P6: 52311178
P7: 44
P8: 0
P9: System.InvalidOperationException
P10: 

Attached files:
C:\Users\spiffomatic64\AppData\Local\Temp\WERFE6.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_niui.exe_6a3fe03e3b8782e20236cb76f21ff836e9a919_0cc6279a

Analysis symbol: 
Rechecking for solution: 0
Report Id: 41d5adf0-51c6-11e4-aa25-0019dbb6535f
Report Status: 0

**Comment by falahati** [comment]
This should be fixed in the latest version
